# Generated by Django 4.0.4 on 2022-06-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_group', models.CharField(max_length=1, verbose_name='Group')),
                ('match_date', models.DateField(verbose_name='Date')),
                ('match_time', models.TimeField(verbose_name='Time')),
                ('home_team', models.CharField(max_length=50, verbose_name='Home')),
                ('away_team', models.CharField(max_length=50, verbose_name='Away')),
                ('home_goals', models.IntegerField(verbose_name='Home Goals')),
                ('away_goals', models.IntegerField(verbose_name='Away Goals')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
